### PR TITLE
Add missing default value functionality to config

### PR DESCRIPTION
**Pull request by movingobjects**
The val method of the ConfigModel is meant to have this default value
second argument (in case the config field doesn’t exist), and somehow
never made it in (despite being expected in a number of places in the
code).

### CODE REVIEW

**Comment by movingobjects** [comment]
@surreal8 @wjrro Did I do this pull request right? It looks like the code was merged in c54da456547cb1d9833f2d6532f8ad27672ef315, but this is still sitting here. I've got another small update coming, so want to make sure I'm doing these right. I'm thinking I should have created a branch specifically for this change—is that right?

**Comment by L4Z3RC47** [comment]
@sccottt It looks like there aren't any file changes in this PR. You're doing the pull requests properly, not sure why this one is sitting here like that. Closing this request.

**Comment by alexburner** [comment]
Looks like @surreal8 merged in the changes in a way that circumvented the PR? And now GitHub is confused?

**Comment by alexburner** [comment]
https://github.com/art-institute-of-chicago/journeymaker-client/commit/c54da456547cb1d9833f2d6532f8ad27672ef315

**Pull request closed without merging**
